Missing cstdio
Under Fedora 38 g++ (GCC) 13.0.1 I was getting:

vk_mem_alloc.h:2839:5: error: ‘snprintf’ was not declared in this scope
 2839 |     snprintf(outStr, strLen, "%u", static_cast<unsigned int>(num));